DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    AUTHORITY VARCHAR(5) NOT NULL
);